### ISSUE TITLE
[Bug] Recipe Error on load with Botania + Advanced Botany

### ISSUE THREAD

**Issue by Pilzinsel64** [GTNewHorizons/Advanced-Botany#6]
When only installed Botania + Advanced Botania, loading Minecraft fails with an error shown below.

This change may cause it:
https://github.com/GTNewHorizons/Advanced-Botany/pull/5/files#diff-df2d622e477c1f5620cecd5a8167b745a4662d2dab87b47ed8bdebe6850cf2e8R217-R252

Error:
```
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:630)
	at ab.common.lib.register.RecipeListAB.setupCrafting(RecipeListAB.java:225)
	at ab.common.lib.register.RecipeListAB.postInit(RecipeListAB.java:140)
	at ab.utils.ModHelperManager.postInit(ModHelperManager.java:20)
	at ab.common.core.proxy.CommonProxy.postInit(CommonProxy.java:41)
	at ab.client.core.proxy.ClientProxy.postInit(ClientProxy.java:82)
	at ab.AdvancedBotany.postInit(AdvancedBotany.java:42)
	...
```

Any idea how we could fix this? I even have troubles setting up the workspace, so maybe one with more insights (regarding mod materials and items) can take a look to this. :)

**Comment by Dream-Master** [comment]
@Pilzinsel64 maybe it need botanic horizons ? or gt?

**Comment by Pilzinsel64** [comment]
@Dream-Master Probably, but the only depency in MC shown is Botania. I assume it wants an Ore from OreDictionary that gets added by one of the two mods you said.
It can be fixed probably but I have no clue about the materials used here.

**Comment by EnderProyects** [comment]
If you are using my fork, I changed recipes to use gregtech materials, also in the graddle dependencies there should be

**Comment by Pilzinsel64** [comment]
@EnderProyects Not sure what you exactly mean with "I change recipes to use gretech materials", because I tested your build and it loads fine without GregTech. Recipes seems to be there mosty. But I have no clue about Botania yet, so I need to ask my parter (she asked for Advanced Botania). :D

**Comment by EnderProyects** [comment]
The materials are: thaumcraft items ( already used in the main code so it should be a dependency, gt gems, gt plates, gt twilight materials, and botania materials

**Comment by Pilzinsel64** [comment]
My partner said that everything seems to be craftable and should be good enough to install (using fork of @EnderProyects + without having GregTech installed). 👍

**Comment by EnderProyects** [comment]
Well, there are some things left to do:

1, upgrade the lang file with Alastor texts
2, change some recipes I missed to plates✅
3, make a plate version of magic Mithrill or oredict it
4, place catalyst for nei recipes
5,make the armour set crafteable in a botania infusion instead of a crafting table, or a thaum infusion ✅

**Comment by Alastors** [comment]
> Well, there are some things left to do:
> 
> 1, upgrade the lang file with Alastor texts 2, change some recipes I missed to plates✅ 3, make a plate version of magic Mithrill or oredict it 4, place catalyst for nei recipes 5,make the armour set crafteable in a botania infusion instead of a crafting table, or a thaum infusion ✅

you were told not to make a new mithril...

**Comment by EnderProyects** [comment]
¿? I didnt make any new mithril lmao

**Comment by Alastors** [comment]
3, make a plate version of magic Mithrill or oredict it

**Comment by Alastors** [comment]
oredict it, don't make a plate version

**Comment by EnderProyects** [comment]
This conversation is weeks earlier lmao

**Comment by Alastors** [comment]
The magic mithril one was yes, but the one I'm commenting on now is only a week old

**Comment by EnderProyects** [comment]
Is of more of a month ago... We are in JUNE

**Comment by Alastors** [comment]
Right, forgot about May

**Comment by EnderProyects** [comment]
P.s Also I dont know why this issue is still opened since it was fixed

**Comment by Alastors** [comment]
Easy fix
